# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_match_code', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('team_1', models.CharField(max_length=40)),
                ('team_2', models.CharField(max_length=40)),
                ('hltv_link', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='demo_file',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='match_code',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='team_2',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analyzer.MatchInfo'),
            preserve_default=False,
        ),
    ]
