# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('played_map', models.CharField(max_length=20)),
                ('t_score', models.IntegerField()),
                ('ct_score', models.IntegerField()),
                ('win_reason', models.CharField(max_length=20)),
                ('team_1', models.CharField(max_length=40)),
                ('team_2', models.CharField(max_length=40)),
                ('match_code', models.CharField(max_length=20)),
                ('demo_file', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=4, max_digits=6)),
                ('XPos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('YPos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('ZPos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('nade_type', models.CharField(max_length=15)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.GameInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=4, max_digits=6)),
                ('team', models.CharField(max_length=20)),
                ('playernum', models.IntegerField()),
                ('XPos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('YPos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('ZPos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('weapon', models.CharField(max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.GameInfo')),
            ],
        ),
    ]
